#!/bin/sh

# This script exists with the sole purpose of executing the Python program.

# TODO: install any dependencies in a venv before executing
# venv_name=8puzzle-solver-venv
# python3 -m venv $venv_name
# source $venv_name/bin/activate

python3 solver/main.py $@
